modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL = "https://github.com/Andre601/ItemsAdderAdvancedTooltip"
license = "MIT"

[[mods]]
modId = "iaat"
version = "${version}"
displayName = "ItemsAdderAdvancedTooltip"
authors = "Andre601"
description = '''
Replaces the "minecraft:id" tooltip text with ItemsAdder's custom one.
'''
logoFile = "assets/iaat/iaat_icon.png"

[[dependencies.iaat]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.iaat]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"
